from dataclasses import dataclass
from google import genai
from google.genai import types
from backend.schemas import DocumentRequest
from utils.config import Settings
from utils.text_utils import parse_terms, sanitize_text
@dataclass
class GeminiDocumentGenerator:
    settings: Settings
    def _prompt(self,r: DocumentRequest)->str:
        terms="\n".join(f"{i}. {t}" for i,t in enumerate(parse_terms(r.terms),1))
        return f'''You are the document-drafting component of LegalEase. Create a professional legal-document DRAFT from the facts below. Do not invent material facts; use [MISSING: item] for important missing information. Return plain text only. Start with the document title in uppercase. Include a NOTICE stating this is an AI-generated draft requiring appropriate legal review. Include appropriate sections and signature blocks. Do not claim legal validity, attorney review, or jurisdiction compliance.\n\nDocument type: {r.document_type}\nParties: {r.parties}\nEffective date: {r.effective_date}\nTerms:\n{terms}'''
    def _demo(self,r: DocumentRequest)->str:
        return sanitize_text(f'''{r.document_type.upper()}\n\nNOTICE\nThis is a demonstration draft generated by LegalEase. It is not legal advice and must be reviewed for jurisdiction-specific requirements before use.\n\n1. PARTIES\n{r.parties}\n\n2. EFFECTIVE DATE\n{r.effective_date}\n\n3. TERMS AND CONDITIONS\n{chr(10).join('- '+x for x in parse_terms(r.terms))}\n\n4. GENERAL PROVISIONS\nReview and complete any missing provisions required for the intended transaction.\n\n5. SIGNATURES\nParty 1: ______________________________\nName: ________________________________\nDate: _________________________________\n\nParty 2: ______________________________\nName: ________________________________\nDate: _________________________________''')
    def generate_document(self,r: DocumentRequest)->str:
        if self.settings.demo_mode: return self._demo(r)
        if not self.settings.gemini_api_key: raise RuntimeError("GEMINI_API_KEY is not configured. Add it to .env or set DEMO_MODE=true.")
        client=genai.Client(api_key=self.settings.gemini_api_key)
        response=client.models.generate_content(model=self.settings.gemini_model, contents=self._prompt(r), config=types.GenerateContentConfig(temperature=0.2,max_output_tokens=8192))
        content=getattr(response,"text",None)
        if not content: raise RuntimeError("Gemini returned an empty response.")
        return sanitize_text(content)
